### ISSUE TITLE
Heard of Mun-lang?

### ISSUE THREAD

**Issue by erlend-sh** [Tyg13/tylang#1]
Hey!

I'm on the board of the Rust GameDev WG as well as the Amethyst Foundation. I frequently go on "project safaris", which led me to your project. I wonder if you've heard about the Mun language:

https://mun-lang.org/blog/2020/05/16/release-mun-v0-2-0/

I've been engaging with them in an advisor capacity and I'm sending smart people their way every chance I get. They're really nice guys, and their many years of professional gamedev experience vastly increases their chance of getting Mun into mainstream use. Should you ever be on the lookout for a new challenge in language development, I hope you'll check out what they're working on!

Sincerely,

Erlend

**Comment by Tyg13** [comment]
Hi, Erlend!

Unfortunately, I'm probably not what you're looking for -- I'm just a hobbyist, I don't know much about implementing a production programming language -- nor do I really have much time to commit beyond what little I push to GitHub. All the same, I'll definitely keep an eye on Mun. I checked out the 
examples on the main site and it seems like amazing stuff! I particularly liked the hot reload demonstration -- very impressive.

All the same, I appreciate your dropping me a line! I'll be sure to keep Mun in mind in the future.

Thanks,
Tyler
